# ~/.config/foot/foot.ini

# --- FONT E ASPETTO ---
# Riprende font-size=12. Sostituisci "Fira Code" con il font che preferisci.
font=Fira Code:size=12
# Foot usa "pad" per indicare X e Y assieme (window-padding-x = 12, window-padding-y = 12)
pad=12x12

# --- COMPORTAMENTO ---
[scrollback]
# scrollback-limit = 3023
lines=3023

[cursor]
# cursor-style = block e cursor-style-blink = true
style=block
blink=yes

[mouse]
# mouse-hide-while-typing = true
hide-when-typing=yes

[csd]
# window-decoration = false
# Questo dice a Foot di non usare la barra del titolo lato client
preferred=none

[key-bindings]
# Keybindings di base tradotti per Foot
spawn-terminal=Control+Shift+n
font-increase=Control+plus Control+equal
font-decrease=Control+minus
font-reset=Control+0


[colors-dark]
# background-opacity = 1.0
alpha=1.0

foreground=e0e2e8
background=101418
selection-foreground=e0e2e8
selection-background=0d47a1
cursor = 101418 42a5f5

regular0=101418
regular1=ff3270
regular2=42f558
regular3=fff332
regular4=1c8de8
regular5=003e71
regular6=42a5f5
regular7=e8f4ff
bright0=8d979f
bright1=ff739e
bright2=7cff8d
bright3=fff77c
bright4=60b8ff
bright5=7cc4ff
bright6=abd9ff
bright7=f5faff

dim-blend-towards=black
